# Generated by Django 4.2.4 on 2023-09-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Coursetb',
        ),
        migrations.RenameModel(
            old_name='Syllabus',
            new_name='Syllabustb',
        ),
    ]
