# Generated by Django 4.2.4 on 2023-08-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='firstname', max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20, verbose_name='surname')),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
