# Generated by Django 4.2.4 on 2023-09-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temptb',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
