# Generated by Django 4.2.4 on 2023-08-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewtb',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
