# Generated by Django 4.2.4 on 2023-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewtb',
            old_name='mod_id',
            new_name='reg_id',
        ),
    ]
