# Generated by Django 4.2.4 on 2023-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vazhitb',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('vazhi_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
